git:
  depth: 1
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  include:
  - os: osx
    node_js: 6
  - os: windows
    node_js: 6

cache:
  yarn: true
  directories:
  - node_modules
script: yarn test --maxWorkers=4 && yarn flow
