git:
  depth: 1
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
matrix:
  include:
  - os: osx
  - os: windows

cache:
  yarn: true
  directories:
  - node_modules
script: yarn test --maxWorkers=4 && yarn flow
